name: Challenge Tests
# on:
# workflow_dispatch:
# push:
#     branches:
#         - master

on: [push]
# on:
#     workflow_dispatch:
#     push:
#         branches: [main]
#     pull_request:
#         branches: [main]

jobs:
    tests:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run tests:docker
            # - uses: actions/upload-artifact@master
            #   with:
            #       name: allure-results
            #       path: allure-results
            #       retention-days: 20
            - name: List files in the repository
              run: ls ${{ github.workspace }}

            - name: Get Allure History
              uses: actions/checkout@v3
              if: always()
              continue-on-error: true
              with:
                  ref: gh-pages
                  path: gh-pages

            - name: Generate Allure Report
              uses: simple-elf/allure-report-action@master
              if: always()
              with:
                  allure_results: allure-results
                  gh_pages: gh-pages
                  allure_report: allure-report
                  allure_history: allure-history
                  keep_reports: 20

            - name: Deploy Allure Report to GitHub Pages
              if: always()
              uses: peaceiris/actions-gh-pages@v2
              env:
                  PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: allure-history

            - name: Post the link to the report
              if: always()
              uses: Sibz/github-status-action@v1
              with:
                  authToken: ${{secrets.GITHUB_TOKEN}}
                  context: 'Test report'
                  state: 'success'
                  sha: ${{ github.event.pull_request.head.sha }}
                  target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
